spring.application.name=shipment.tracker

# ===============================
# H2 DATABASE CONFIG
# ===============================
#spring.datasource.url=jdbc:h2:mem:shipment-db
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE (Browser UI)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Redis cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# optional tuning
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false